<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lecturer extends \AppBundle\Entity\Lecturer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'lecturer_id', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'staff_id', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'surname', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'othername', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'firstname', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'mobile', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'sex', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'mstatus', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'passport'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'lecturer_id', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'staff_id', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'surname', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'othername', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'firstname', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'mobile', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'sex', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'mstatus', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Lecturer' . "\0" . 'passport'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lecturer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getStudentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudentId', []);

        return parent::getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStaffId($staffId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStaffId', [$staffId]);

        return parent::setStaffId($staffId);
    }

    /**
     * {@inheritDoc}
     */
    public function getStaffId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStaffId', []);

        return parent::getStaffId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', [$surname]);

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', []);

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setOthername($othername)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOthername', [$othername]);

        return parent::setOthername($othername);
    }

    /**
     * {@inheritDoc}
     */
    public function getOthername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOthername', []);

        return parent::getOthername();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', [$mobile]);

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', []);

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSex($sex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', [$sex]);

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function getSex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', []);

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function setMstatus($mstatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMstatus', [$mstatus]);

        return parent::setMstatus($mstatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getMstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMstatus', []);

        return parent::getMstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassport($passport)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassport', [$passport]);

        return parent::setPassport($passport);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassport', []);

        return parent::getPassport();
    }

    /**
     * {@inheritDoc}
     */
    public function getLecturerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLecturerId', []);

        return parent::getLecturerId();
    }

}
