<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Attachment extends \AppBundle\Entity\Attachment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Attachment' . "\0" . 'attachment_id', '' . "\0" . 'AppBundle\\Entity\\Attachment' . "\0" . 'course_id', '' . "\0" . 'AppBundle\\Entity\\Attachment' . "\0" . 'attachment', '' . "\0" . 'AppBundle\\Entity\\Attachment' . "\0" . 'attachment_desc'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Attachment' . "\0" . 'attachment_id', '' . "\0" . 'AppBundle\\Entity\\Attachment' . "\0" . 'course_id', '' . "\0" . 'AppBundle\\Entity\\Attachment' . "\0" . 'attachment', '' . "\0" . 'AppBundle\\Entity\\Attachment' . "\0" . 'attachment_desc'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Attachment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAttachmentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachmentId', []);

        return parent::getAttachmentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourseId($courseId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourseId', [$courseId]);

        return parent::setCourseId($courseId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseId', []);

        return parent::getCourseId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourseTitle($courseTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourseTitle', [$courseTitle]);

        return parent::setCourseTitle($courseTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourseTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourseTitle', []);

        return parent::getCourseTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttachment($attachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttachment', [$attachment]);

        return parent::setAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachment', []);

        return parent::getAttachment();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttachmentDesc($attachmentDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttachmentDesc', [$attachmentDesc]);

        return parent::setAttachmentDesc($attachmentDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachmentDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachmentDesc', []);

        return parent::getAttachmentDesc();
    }

}
